# Cloudflare Pages配置文件

[build]
command = "npm install && npm run build"
publish = "out"
base = "/"

[build.environment]
NODE_VERSION = "18"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200 